name: "SFELAPCO Generation Charge Monitor"
description: "Monitor SFELAPCO monthly generation charges and electricity rates"
version: "1.0.1"
slug: "sfelapco"
init: false
# image: "ghcr.io/yourusername/sfelapco-{arch}"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  update_interval: 1.0
  retain_history: true
  max_history_days: 365
schema:
  update_interval: float(0.1,30.0)
  retain_history: bool
  max_history_days: int(1,1095)
services:
  - mqtt:want
ingress: true
panel_icon: "mdi:lightning-bolt"
panel_header: "SFELAPCO Generation Charge Monitor"